18-rails-auth/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :users, only: [:new, :create]
  get '/login', to: 'sessions#new', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

18-rails-auth/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validate :date_cannot_be_in_the_past, :doctor_cannot_be_unavailable, :time_cannot_be_outside_opening_hours, :patient_cannot_be_unavailable

  def date_as_object
    Date.parse(self.date)
  end

  def date_cannot_be_in_the_past
    if self.date_as_object < Date.today
      errors.add(:date, "must be in the future")
    end
  end

  def doctor_cannot_be_unavailable
    clashing_appt = self.doctor.appointments.find {|appt| appt.date == self.date && appt.time == self.time }
    if clashing_appt
      errors.add(:"doctor #{self.doctor.name}", "is not available at that time")
    end
  end

  def time_cannot_be_outside_opening_hours
    hour = self.time.to_i
    if hour < 9 || hour > 16
      errors.add(:time, "must be between 09:00 and 17:00")
    end
  end

  def patient_cannot_be_unavailable
    clashing_appt = self.patient.appointments.find {|appt| appt.date == self.date && appt.time == self.time }
    if clashing_appt
      errors.add(:"patient #{self.patient.name}", "is not available at that time")
    end
  end

end

18-rails-auth/app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments
    has_many :patients, -> { distinct },  through: :appointments
    validates :name, uniqueness: true
    validates :speciality, presence: true
end

18-rails-auth/app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :doctors, -> { distinct }, through: :appointments
end

18-rails-auth/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

18-rails-auth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?
    helper_method :authorize_user
    before_action :set_current_user

    def set_current_user
        @current_user = session[:user_id] ? User.find(session[:user_id]) : nil
    end

    def logged_in?
        !!@current_user
    end

    def authorize_user
        if !logged_in?
            flash[:notice] = "you must be logged in to view that page"
            redirect_to login_path
        end
    end

end

18-rails-auth/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    before_action :authorize_user, only: [:new, :create]

    def new
        @appointment = Appointment.new
        @doctor = params[:doctor_id] ? Doctor.find(params[:doctor_id]) : nil
        @patient = params[:patient_id] ? Patient.find(params[:patient_id]) : nil
    end

    def create
        appointment = Appointment.create appointment_params
        if appointment.valid?
            redirect_to appointment
        else
            flash[:errors] = appointment.errors.full_messages
            redirect_to new_appointment_path
        end
    end

    def show
        @appointment = Appointment.find params[:id]
    end

    private

    def appointment_params
        params.require(:appointment).permit(:date, :time, :doctor_id, :patient_id)
    end
end

18-rails-auth/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

    def new
        if flash[:doctor_params]
            @doctor = Doctor.create flash[:doctor_params]
            flash[:doctor_params] = nil
        else
            @doctor = Doctor.new
        end
    end

    def create
        @doctor = Doctor.create doctor_params
        if @doctor.valid?
            redirect_to @doctor
        else
            flash[:errors] = @doctor.errors.full_messages
            # render :new   - not nice because now the URL is /doctors not /doctors/new
            flash[:doctor_params] = doctor_params # not nice because it feels kinda hacky, and new needs the logic, too
            redirect_to new_doctor_path
        end
    end

    def index
        @doctors = Doctor.all
    end

    def show
        @doctor = Doctor.find params[:id]
    end

    def destroy
        doctor = Doctor.find params[:id]
        doctor.destroy
        flash[:notice] = "Doctor #{doctor.name} succcessfully deleted"
        redirect_to doctors_path
    end

    private

    def doctor_params
        params.require(:doctor).permit(:name, :speciality)
    end
end

18-rails-auth/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def new
        @patient = Patient.new
    end

    def create
        patient = Patient.create patient_params
        redirect_to patient
        # redirect_to patient_path(patient)
    end

    def index
        @patients = Patient.all
    end

    def show
        @patient = Patient.find params[:id]
    end

    private

    def patient_params
        params.require(:patient).permit(:name, :disease)
    end
end

18-rails-auth/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.find_by(email: params[:user][:email])
        if user && user.authenticate(password: params[:user][:password])
            session[:user_id] = user.id
            redirect_to doctors_path
        else
            flash[:errors] = ["Sorry, that account is not found"]
            redirect_to login_path
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to login_path
    end
end

18-rails-auth/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.create user_params
        if user.valid?
            session[:user_id] = user.id
            redirect_to doctors_path
        else
            flash[:errors] = user.errors.full_messages
            redirect_to new_user_path
        end
    end

    private 

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

18-rails-auth/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

18-rails-auth/app/helpers/doctors_helper.rb
module DoctorsHelper
end

18-rails-auth/app/helpers/patients_helper.rb
module PatientsHelper
end

18-rails-auth/app/helpers/sessions_helper.rb
module SessionsHelper
end

18-rails-auth/app/helpers/users_helper.rb
module UsersHelper
end

18-rails-auth/app/views/appointments/new.html.erb
<%= form_for @appointment do |form| %>
    <%= form.label :doctor_id %>
    <% if @doctor %>
        <p><%= @doctor.name %></p>
        <%= form.hidden_field :doctor_id, value: @doctor.id %>
    <% else %>
        <%= form.collection_select :doctor_id, Doctor.all, :id, :name %>
    <% end%>
    <%= form.label :patient_id %>
    <% if @patient %>
        <p><%= @patient.name %></p>
        <%= form.hidden_field :patient_id, value: @patient.id %>
    <% else %>
        <%= form.collection_select :patient_id, Patient.all, :id, :name %>
    <% end%>
    <%= form.label :date %>
    <%= form.date_field :date %>
    <%= form.label :time %>
    <%= form.time_field :time %>
    <%= form.submit %>
<% end %>

18-rails-auth/app/views/appointments/show.html.erb
<div>
Doctor: <%= link_to @appointment.doctor.name, @appointment.doctor %>
</div>
<div>
Patient: <%= link_to @appointment.patient.name, @appointment.patient %>
</div>
<div>
<%= @appointment.date %> at <%= @appointment.time %>
</div>

18-rails-auth/app/views/doctors/index.html.erb
<% @doctors.each do |doctor| %>
    <div>
    <%= link_to doctor.name, doctor%>
    </div>
<% end %>

18-rails-auth/app/views/doctors/new.html.erb
<%= form_for @doctor do |form| %>
    <%= form.label :name do %>
        <h2>namme </h2>
    <% end %>
    <%= form.text_field :name %>
    <%= form.label :speciality %>
    <%= form.text_field :speciality %>
    <%= form.submit %>
<% end %>

18-rails-auth/app/views/doctors/show.html.erb
<h2><%= @doctor.name %></h2>
<h2><%= @doctor.speciality %></h2>

<% @doctor.patients.each do |patient| %>
    <div>
    <%= link_to patient.name, patient %> or <%= link_to 'book appointment with this doctor and patient', new_appointment_path({ doctor_id: @doctor.id, patient_id: patient.id}) %>
    </div>
<% end %>

<%= link_to 'book appointment with this doctor', new_appointment_path({ doctor_id: @doctor.id}) %>
<%= link_to 'delete this doctor', doctor_path(@doctor), {method: 'delete'} %>

18-rails-auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsOffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'all doctors', doctors_path %>
    <%= link_to 'all patients', patients_path %>
    <%= link_to 'new doctor', new_doctor_path %>
    <%= link_to 'new patient', new_patient_path %>
    <%= link_to 'new appointment', new_appointment_path %>
    <% if logged_in? %>
      hello <%= @current_user.email %>!<%= link_to 'log out', logout_path, { method: 'delete' } %>
    <% else %>
      <%= link_to 'log in', login_path %> or <%= link_to 'sign up', new_user_path %>
    <% end %>
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <p class="error"><%= error %></p?>
        <% end %>
    <% end %>
    <% if flash[:notice] %>
        <div>
            <%= flash[:notice] %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

18-rails-auth/app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
<% end %>