15-rails-forms-validations/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

15-rails-forms-validations/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def new
        @appointment = Appointment.new
        @doctor = params[:doctor_id] ? Doctor.find(params[:doctor_id]) : nil
        @patient = params[:patient_id] ? Patient.find(params[:patient_id]) : nil
    end

    def create
        appointment = Appointment.create appointment_params
        if appointment.valid?
            redirect_to appointment
        else
            flash[:errors] = appointment.errors.full_messages
            redirect_to new_appointment_path
        end
    end

    def show
        @appointment = Appointment.find params[:id]
    end

    private

    def appointment_params
        params.require(:appointment).permit(:date, :time, :doctor_id, :patient_id)
    end
end

15-rails-forms-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsOffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'all doctors', doctors_path %>
    <%= link_to 'all patients', patients_path %>
    <%= link_to 'new doctor', new_doctor_path %>
    <%= link_to 'new patient', new_patient_path %>
    <%= link_to 'new appointment', new_appointment_path %>
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <p class="error"><%= error %></p?>
        <% end %>
    <% end %>
    <% if flash[:notice] %>
        <div>
            <%= flash[:notice] %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>