13-rails-forms-crud/config/routes.rb
Rails.application.routes.draw do
  resources :species
  resources :pets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

13-rails-forms-crud/app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :species
end

13-rails-forms-crud/app/models/species.rb
class Species < ApplicationRecord
    has_many :pets
end

13-rails-forms-crud/app/controllers/pets_controller.rb
<%= f.label :user_id %>
  <% if @user %>
      <p><%= @user.name %></p>
      <%= form.hidden_field :user_id, value: @user.id %>class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def new
    @species_for_select = Species.all.map{|species| [species.name, species.id]}
  end

  def create
    pet = Pet.create params.require(:pet).permit(:name, :age, :species_id)
    redirect_to pet_path(pet)
  end

  def edit
    @pet = Pet.find params[:id]
    @species_for_select = Species.all.map{|species| [species.name, species.id]}
  end

  def update
    pet = Pet.find params[:id]
    pet.update params.require(:pet).permit(:name, :age, :species_id)
    redirect_to pet_path(pet)
  end

  def show
    @pet = Pet.find params[:id]
  end

  def destroy
    pet = Pet.find params[:id]
    pet.destroy
    redirect_to pets_path
  end
end

13-rails-forms-crud/app/controllers/species_controller.rb
class SpeciesController < ApplicationController

    before_action :find_species, only: [:edit, :update]

    def new
        @species = Species.new
    end

    def create
        species = Species.create species_params
        redirect_to new_pet_path
    end

    def edit
    end

    def update
        @species.update species_params
        redirect_to new_pet_path
    end

    private

    def find_species
        @species = Species.find params[:id]
    end

    def species_params
        params.require(:species).permit(:name)
    end

end

13-rails-forms-crud/app/helpers/pets_helper.rb
module PetsHelper
end

13-rails-forms-crud/app/helpers/species_helper.rb
module SpeciesHelper
end

13-rails-forms-crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'all pets', pets_path %>
    <%= link_to 'new pet', new_pet_path %>
    <%= link_to 'new species', new_species_path %>
    <%= yield %>
  </body>
</html>

13-rails-forms-crud/app/views/pets/edit.html.erb
<h2>new pet</h2>
<%= form_tag(pet_path(@pet), method: 'patch') do %>
    <%= text_field_tag :'pet[name]', @pet.name %>
    <%= number_field_tag :'pet[age]', @pet.age %>
    <%= select_tag :'pet[species_id]', options_for_select(@species_for_select, @pet.species_id) %>
    <%= submit_tag %>
<% end %>
<%= link_to 'delete this pet', pet_path(@pet), {method: 'delete', data: { confirm: 'Are you sure?' }}  %>

13-rails-forms-crud/app/views/pets/index.html.erb
<h1>Pets</h1>
<% @pets.each do |pet| %>
<p><%= link_to pet.name, pet_path(pet) %> the <%= pet.species.name %></p>
<% end %>

13-rails-forms-crud/app/views/pets/new.html.erb
<h2>new pet</h2>
<%= form_tag pets_path do %>
    <%= text_field_tag :'pet[name]'%>
    <%= number_field_tag :'pet[age]' %>
    <%= select_tag :'pet[species_id]', options_for_select(@species_for_select) %>
    <%= submit_tag %>
<% end %>

13-rails-forms-crud/app/views/pets/show.html.erb
<h1><%= @pet.name %> is a <%= link_to @pet.species.name, species_path(@pet.species) %></h1>
<p><%= @pet.age %> years old</p>
<%= link_to 'edit this pet', edit_pet_path(@pet) %>